<?php
namespace App\Controller;
class MockData{

    public static $data1 = [
        [
            "province" => "Italy",
            "departement" => "Lombardia",
            "commune" => "Acquafredda",
            "bureauVote" => "GUE003",
            "votant" => "9883",
            "bulletinNuls" => "45",
            "suffrageExp" => "25",
            "voteOui" => "174",
            "voteNon" => "424",
            "date" => "11-16-2023",
            "idSubmitter" => "3712",
            "codePV" => "151"
        ],
        [
            "province" => "South Africa",
            "departement" => "Limpopo",
            "commune" => "Phalaborwa",
            "bureauVote" => "PAL006",
            "votant" => "2974",
            "bulletinNuls" => "59",
            "suffrageExp" => "17",
            "voteOui" => "227",
            "voteNon" => "355",
            "date" => "12-6-2023",
            "idSubmitter" => "8851",
            "codePV" => "856"
        ],
        [
            "province" => "Italy",
            "departement" => "Umbria",
            "commune" => "Todi",
            "bureauVote" => "TOR003",
            "votant" => "8329",
            "bulletinNuls" => "15",
            "suffrageExp" => "70",
            "voteOui" => "455",
            "voteNon" => "303",
            "date" => "16-28-2023",
            "idSubmitter" => "7806",
            "codePV" => "604"
        ],
        [
            "province" => "South Africa",
            "departement" => "Free State",
            "commune" => "Phuthaditjhaba",
            "bureauVote" => "TOR004",
            "votant" => "9975",
            "bulletinNuls" => "37",
            "suffrageExp" => "10",
            "voteOui" => "323",
            "voteNon" => "155",
            "date" => "16-13-2023",
            "idSubmitter" => "8183",
            "codePV" => "192"
        ],
        [
            "province" => "Nigeria",
            "departement" => "Niger",
            "commune" => "Minna",
            "bureauVote" => "BON004",
            "votant" => "7004",
            "bulletinNuls" => "28",
            "suffrageExp" => "13",
            "voteOui" => "343",
            "voteNon" => "154",
            "date" => "10-25-2023",
            "idSubmitter" => "1661",
            "codePV" => "512"
        ],
        [
            "province" => "Nigeria",
            "departement" => "Anambra",
            "commune" => "Onitsha",
            "bureauVote" => "KEN006",
            "votant" => "9372",
            "bulletinNuls" => "73",
            "suffrageExp" => "50",
            "voteOui" => "315",
            "voteNon" => "207",
            "date" => "16-58-2023",
            "idSubmitter" => "1357",
            "codePV" => "954"
        ],
        [
            "province" => "South Africa",
            "departement" => "Mpumalanga",
            "commune" => "Emalahleni",
            "bureauVote" => "73",
            "votant" => "3683",
            "bulletinNuls" => "49",
            "suffrageExp" => "90",
            "voteOui" => "281",
            "voteNon" => "433",
            "date" => "17-0-2023",
            "idSubmitter" => "2334",
            "codePV" => "197"
        ],
        [
            "province" => "South Africa",
            "departement" => "KwaZulu-Natal",
            "commune" => "Umlazi",
            "bureauVote" => "43",
            "votant" => "2240",
            "bulletinNuls" => "53",
            "suffrageExp" => "33",
            "voteOui" => "410",
            "voteNon" => "329",
            "date" => "11-35-2023",
            "idSubmitter" => "3486",
            "codePV" => "925"
        ],
        [
            "province" => "South Africa",
            "departement" => "Limpopo",
            "commune" => "Giyani",
            "bureauVote" => "58",
            "votant" => "4753",
            "bulletinNuls" => "90",
            "suffrageExp" => "14",
            "voteOui" => "288",
            "voteNon" => "51",
            "date" => "13-52-2023",
            "idSubmitter" => "5336",
            "codePV" => "401"
        ],
        [
            "province" => "Italy",
            "departement" => "Trentino-Alto Adige",
            "commune" => "Giustino",
            "bureauVote" => "17",
            "votant" => "6266",
            "bulletinNuls" => "59",
            "suffrageExp" => "19",
            "voteOui" => "133",
            "voteNon" => "351",
            "date" => "12-56-2023",
            "idSubmitter" => "5478",
            "codePV" => "250"
        ],
        [
            "province" => "South Africa",
            "departement" => "Limpopo",
            "commune" => "Polokwane",
            "bureauVote" => "25",
            "votant" => "7091",
            "bulletinNuls" => "53",
            "suffrageExp" => "76",
            "voteOui" => "123",
            "voteNon" => "389",
            "date" => "14-41-2023",
            "idSubmitter" => "5455",
            "codePV" => "757"
        ],
        [
            "province" => "Italy",
            "departement" => "Toscana",
            "commune" => "Gavorrano",
            "bureauVote" => "61",
            "votant" => "9988",
            "bulletinNuls" => "18",
            "suffrageExp" => "34",
            "voteOui" => "452",
            "voteNon" => "146",
            "date" => "17-26-2023",
            "idSubmitter" => "9821",
            "codePV" => "855"
        ],
        [
            "province" => "South Africa",
            "departement" => "Mpumalanga",
            "commune" => "Emalahleni",
            "bureauVote" => "29",
            "votant" => "7653",
            "bulletinNuls" => "48",
            "suffrageExp" => "21",
            "voteOui" => "233",
            "voteNon" => "245",
            "date" => "15-52-2023",
            "idSubmitter" => "9298",
            "codePV" => "479"
        ],
        [
            "province" => "South Africa",
            "departement" => "Eastern Cape",
            "commune" => "Alice",
            "bureauVote" => "3",
            "votant" => "1087",
            "bulletinNuls" => "60",
            "suffrageExp" => "34",
            "voteOui" => "304",
            "voteNon" => "268",
            "date" => "11-19-2023",
            "idSubmitter" => "9756",
            "codePV" => "881"
        ],
        [
            "province" => "South Africa",
            "departement" => "Gauteng",
            "commune" => "Springs",
            "bureauVote" => "89",
            "votant" => "5036",
            "bulletinNuls" => "10",
            "suffrageExp" => "99",
            "voteOui" => "258",
            "voteNon" => "189",
            "date" => "15-24-2023",
            "idSubmitter" => "1311",
            "codePV" => "711"
        ],
        [
            "province" => "Italy",
            "departement" => "Emilia-Romagna",
            "commune" => "Modena",
            "bureauVote" => "90",
            "votant" => "8394",
            "bulletinNuls" => "20",
            "suffrageExp" => "59",
            "voteOui" => "219",
            "voteNon" => "250",
            "date" => "14-52-2023",
            "idSubmitter" => "5553",
            "codePV" => "313"
        ],
        [
            "province" => "Nigeria",
            "departement" => "Anambra",
            "commune" => "Okpoko",
            "bureauVote" => "70",
            "votant" => "5773",
            "bulletinNuls" => "60",
            "suffrageExp" => "82",
            "voteOui" => "490",
            "voteNon" => "52",
            "date" => "10-1-2023",
            "idSubmitter" => "9337",
            "codePV" => "274"
        ],
    ];

public static $data2 =[
        [
            "province" => "South Africa",
            "departement" => "Free State",
            "commune" => "Bloemfontein",
            "bureauVote" => "23",
            "votant" => "3068",
            "bulletinNuls" => "37",
            "suffrageExp" => "13",
            "voteOui" => "428",
            "voteNon" => "293",
            "date" => "12-6-2023",
            "idSubmitter" => "7508",
            "codePV" => "412"
        ],
        [
            "province" => "Nigeria",
            "departement" => "Oyo",
            "commune" => "Ibadan",
            "bureauVote" => "32",
            "votant" => "7363",
            "bulletinNuls" => "13",
            "suffrageExp" => "38",
            "voteOui" => "402",
            "voteNon" => "117",
            "date" => "11-25-2023",
            "idSubmitter" => "8888",
            "codePV" => "446"
        ],
        [
            "province" => "South Africa",
            "departement" => "KwaZulu-Natal",
            "commune" => "Pietermaritzburg",
            "bureauVote" => "71",
            "votant" => "3108",
            "bulletinNuls" => "96",
            "suffrageExp" => "65",
            "voteOui" => "244",
            "voteNon" => "187",
            "date" => "11-3-2023",
            "idSubmitter" => "2644",
            "codePV" => "148"
        ],
        [
            "province" => "Nigeria",
            "departement" => "Akwa Ibom",
            "commune" => "Uyo",
            "bureauVote" => "11",
            "votant" => "9322",
            "bulletinNuls" => "61",
            "suffrageExp" => "93",
            "voteOui" => "149",
            "voteNon" => "196",
            "date" => "12-49-2023",
            "idSubmitter" => "9420",
            "codePV" => "767"
        ],
        [
            "province" => "Italy",
            "departement" => "Molise",
            "commune" => "Campobasso",
            "bureauVote" => "71",
            "votant" => "2357",
            "bulletinNuls" => "78",
            "suffrageExp" => "84",
            "voteOui" => "150",
            "voteNon" => "411",
            "date" => "17-45-2023",
            "idSubmitter" => "4350",
            "codePV" => "546"
        ],
        [
            "province" => "Nigeria",
            "departement" => "Imo",
            "commune" => "Okigwe",
            "bureauVote" => "87",
            "votant" => "7500",
            "bulletinNuls" => "85",
            "suffrageExp" => "68",
            "voteOui" => "179",
            "voteNon" => "131",
            "date" => "11-22-2023",
            "idSubmitter" => "7510",
            "codePV" => "146"
        ],
        [
            "province" => "Nigeria",
            "departement" => "Rivers",
            "commune" => "Buguma",
            "bureauVote" => "33",
            "votant" => "6599",
            "bulletinNuls" => "84",
            "suffrageExp" => "20",
            "voteOui" => "421",
            "voteNon" => "251",
            "date" => "16-29-2023",
            "idSubmitter" => "5186",
            "codePV" => "724"
        ],
        [
            "province" => "South Africa",
            "departement" => "KwaZulu-Natal",
            "commune" => "Pinetown",
            "bureauVote" => "45",
            "votant" => "4215",
            "bulletinNuls" => "66",
            "suffrageExp" => "93",
            "voteOui" => "499",
            "voteNon" => "170",
            "date" => "15-54-2023",
            "idSubmitter" => "3942",
            "codePV" => "326"
        ],
        [
            "province" => "Nigeria",
            "departement" => "Benue",
            "commune" => "Otukpo",
            "bureauVote" => "22",
            "votant" => "2926",
            "bulletinNuls" => "15",
            "suffrageExp" => "94",
            "voteOui" => "370",
            "voteNon" => "66",
            "date" => "13-23-2023",
            "idSubmitter" => "5931",
            "codePV" => "974"
        ],
        [
            "province" => "South Africa",
            "departement" => "North West",
            "commune" => "Rustenburg",
            "bureauVote" => "58",
            "votant" => "5779",
            "bulletinNuls" => "29",
            "suffrageExp" => "20",
            "voteOui" => "477",
            "voteNon" => "330",
            "date" => "13-15-2023",
            "idSubmitter" => "6006",
            "codePV" => "676"
        ],
        [
            "province" => "South Africa",
            "departement" => "North West",
            "commune" => "Klerksdorp",
            "bureauVote" => "27",
            "votant" => "9939",
            "bulletinNuls" => "37",
            "suffrageExp" => "17",
            "voteOui" => "164",
            "voteNon" => "215",
            "date" => "16-29-2023",
            "idSubmitter" => "4589",
            "codePV" => "903"
        ],
        [
            "province" => "South Africa",
            "departement" => "Free State",
            "commune" => "Kroonstad",
            "bureauVote" => "61",
            "votant" => "2631",
            "bulletinNuls" => "38",
            "suffrageExp" => "15",
            "voteOui" => "460",
            "voteNon" => "350",
            "date" => "12-31-2023",
            "idSubmitter" => "5148",
            "codePV" => "762"
        ],
        [
            "province" => "Italy",
            "departement" => "Veneto",
            "commune" => "Lozzo Atestino",
            "bureauVote" => "65",
            "votant" => "7686",
            "bulletinNuls" => "57",
            "suffrageExp" => "15",
            "voteOui" => "495",
            "voteNon" => "232",
            "date" => "15-22-2023",
            "idSubmitter" => "1919",
            "codePV" => "829"
        ],
        [
            "province" => "France",
            "departement" => "Franche-Comté",
            "commune" => "Dole",
            "bureauVote" => "72",
            "votant" => "2204",
            "bulletinNuls" => "14",
            "suffrageExp" => "72",
            "voteOui" => "360",
            "voteNon" => "497",
            "date" => "12-40-2023",
            "idSubmitter" => "3399",
            "codePV" => "858"
        ],
    ];

}